name: CI-Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          # npm 模式下，直接指定 cache 为 npm
          cache: 'pnpm'
          # 告诉 GitHub 去哪里找 package-lock.json
          cache-dependency-path: 'frontend/app/pnpm-lock.yaml'

      - name: Install dependencies
        # npm ci 相当于 pnpm install --frozen-lockfile
        # 它专门用于 CI 环境，速度更快且保证版本一致
        run: npm ci
        working-directory: frontend/app

      - name: Lint Check
        run: npm run lint
        working-directory: frontend/app

      - name: Run Tests
        run: npm run test
        working-directory: frontend/app

      - name: Build Check
        run: npm run build
        working-directory: frontend/app